/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import api.telegram.MyTelegram;
import helper.IpValidator;
import java.awt.AWTException;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Enumeration;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MainWindow extends javax.swing.JFrame {

    public TrayIcon trayIcon;
    public SystemTray tray;
    ArrayList clientOutputStreams;
    ArrayList<String> users;

    FileOutputStream fos;
    BufferedOutputStream bos;
    OutputStream output;
    DataOutputStream dos;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        dzilInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelServerLokal = new javax.swing.JPanel();
        labelIpServer = new javax.swing.JLabel();
        labelDirectory = new javax.swing.JLabel();
        textFieldDirectory = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        labelLog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        labelPort = new javax.swing.JLabel();
        labelCopyRight = new javax.swing.JLabel();
        textFieldPort = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanelAboutMe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Server Antrian");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelServerLokal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelIpServer.setText("IP SERVER");

        labelDirectory.setText("DIRECTORY");

        textFieldDirectory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldDirectory.setText("D:\\Server Warehouse");
        textFieldDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDirectoryActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(51, 255, 0));
        btnStart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setToolTipText("");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(204, 0, 51));
        btnStop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnStop.setText("Stop Server");
        btnStop.setToolTipText("");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        labelLog.setText("Log Server");

        textAreaLog.setEditable(false);
        textAreaLog.setColumns(20);
        textAreaLog.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        textAreaLog.setRows(5);
        jScrollPane1.setViewportView(textAreaLog);

        labelPort.setText("PORT");

        labelCopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCopyRight.setText("Copyright By Dzil, Jakarta. V.1.2.0");

        textFieldPort.setEditable(false);
        textFieldPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldPort.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelServerLokalLayout = new javax.swing.GroupLayout(jPanelServerLokal);
        jPanelServerLokal.setLayout(jPanelServerLokalLayout);
        jPanelServerLokalLayout.setHorizontalGroup(
            jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                        .addComponent(labelLog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                        .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIpServer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPort, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                                        .addComponent(btnStart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                        .addComponent(btnStop))
                                    .addComponent(textFieldDirectory)
                                    .addComponent(textFieldPort)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServerLokalLayout.createSequentialGroup()
                                .addComponent(labelCopyRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanelServerLokalLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(5, 5, 5)))
                        .addContainerGap())))
        );
        jPanelServerLokalLayout.setVerticalGroup(
            jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServerLokalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIpServer)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(1, 1, 1)
                .addComponent(labelLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerLokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCopyRight)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Server Lokal ", new javax.swing.ImageIcon(getClass().getResource("/img/cloud-storage-uploading-option.png")), jPanelServerLokal); // NOI18N

        jPanelAboutMe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1553572905122.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanelAboutMeLayout = new javax.swing.GroupLayout(jPanelAboutMe);
        jPanelAboutMe.setLayout(jPanelAboutMeLayout);
        jPanelAboutMeLayout.setHorizontalGroup(
            jPanelAboutMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutMeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAboutMeLayout.setVerticalGroup(
            jPanelAboutMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Me ", new javax.swing.ImageIcon(getClass().getResource("/img/instagram-symbol.png")), jPanelAboutMe); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        textAreaLog.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed

        try {
            Thread.sleep(5000);                 //5000 milliseconds is five second.
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }

        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        textFieldPort.setText("");
        textFieldDirectory.setEnabled(true);

        textAreaLog.setText("");

        URL resource;
        resource = getClass().getResource("/img/favicon-red.png");
        Image image = Toolkit.getDefaultToolkit().getImage(resource);
        setIconImage(image);
        trayIcon.setImage(image);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (textFieldDirectory.getText() != null && !textFieldDirectory.getText().isEmpty()) {
            actionAfterButtonStartClick();

            Thread starter = new Thread(new ServerStart());
            starter.start();

            textAreaLog.append("Main Thread " + starter.getName() + " \n");
        } else {
            textAreaLog.append(this.createLog(
                    "Direktori belum diisi", "Failed"));
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void textFieldDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDirectoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDirectoryActionPerformed

    public void windowIconified(WindowEvent e) {
        setVisible(false);
        System.out.println("Minimixe");
    }

    private void dzilInit() {

//        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/favicon.png")));
        URL resource;
        resource = getClass().getResource("/img/favicon-red.png");

        Image image = Toolkit.getDefaultToolkit().getImage(resource);
        setIconImage(image);

        //Check the SystemTray support
        if (!SystemTray.isSupported()) {
            System.out.println("SystemTray is not supported");
            return;
        }
        PopupMenu popup = new PopupMenu();
        trayIcon = new TrayIcon(image, " Dzil Keren ", popup);
        trayIcon.setImageAutoSize(true);
        tray = SystemTray.getSystemTray();

        MenuItem exitItem = new MenuItem("Exit");

        popup.add(exitItem);
        trayIcon.setPopupMenu(popup);

        try {
            tray.add(trayIcon);
        } catch (AWTException e) {
            System.out.println("TrayIcon could not be added.");
            return;
        }

        trayIcon.addActionListener((ActionEvent e) -> {
            setVisible(true);
        });

        exitItem.addActionListener((ActionEvent e) -> {
            tray.remove(trayIcon);
            System.exit(0);
        });

        try {
            Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();

            //Lopping semua interfaces dan sesuaikan pattern
            IpValidator ipValidator = new IpValidator();
            ArrayList<Object> ipAddresess = new ArrayList<Object>();
            while (interfaces.hasMoreElements()) {
                NetworkInterface networkInterface = interfaces.nextElement();
                // drop inactive
                if (!networkInterface.isUp()) {
                    continue;
                }

                // smth we can explore
                Enumeration<InetAddress> addresses = networkInterface.getInetAddresses();

                while (addresses.hasMoreElements()) {
                    InetAddress addr = addresses.nextElement();
                    boolean matches = ipValidator.validate(addr.getHostAddress());

                    if (matches) {
                        ipAddresess.add(addr.getHostAddress());
                    }
                }
            }

            Collections.reverse(ipAddresess);
            jComboBox1.setModel(new DefaultComboBoxModel(ipAddresess.toArray()));
        } catch (Exception e) {
            e.printStackTrace();
        }

//        try {
//            InetAddress inetAddress = InetAddress.getLocalHost();
//            textFieldIPServer.setText(inetAddress.getHostAddress());
//        } catch (UnknownHostException ex) {
//            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private String getDate() {
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String strDate = formatter.format(date);
        return strDate;
    }

    private String getDateTime() {
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String strDateTime = formatter.format(date);
        return strDateTime;
    }

    private String createLog(String message, String result) {
        StringBuilder sb = new StringBuilder();
        sb.append(this.getDate());
        sb.append("  ");
        sb.append(message);
        sb.append(" : ");
        sb.append(result);
        sb.append("\n");

        return sb.toString();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

//                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");  // This line gives Windows Theme
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private void actionAfterButtonStartClick() {
        btnStart.setEnabled(false);
        //Hidupkan Button Stop
        btnStop.setEnabled(true);

        //Beri Informasi port berapa dia jalan
        textFieldPort.setText(String.valueOf(59090));

        //Cegah User menggeanti tempat direktorinya
        textFieldDirectory.setEnabled(false);

        // Update Icon
        URL resource;
        resource = getClass().getResource("/img/favicon.png");
        Image image = Toolkit.getDefaultToolkit().getImage(resource);
        setIconImage(image);
        trayIcon.setImage(image);
    }

    public class ServerStart implements Runnable {

        @Override
        public void run() {
            try {
                ServerSocket serverSocket = new ServerSocket(59090);
                while (true) {
                    Socket clientSocket = null;
                    clientSocket = serverSocket.accept();

                    // create each thread
                    Thread listener = new Thread(new ClientHandler(clientSocket));
                    listener.start();
                    textAreaLog.append("\n" + "Thread Listering: " + listener.getName() + "\n");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                textAreaLog.append(ex.getMessage());
            }
        }
    }

    public class ClientHandler implements Runnable {

        Socket socket;
        Path path;

        public ClientHandler(Socket clientSocket) {
            try {
                socket = clientSocket;
            } catch (Exception ex) {
                textAreaLog.append(ex.getMessage());
            }
        }

        @Override
        public void run() {
            try {

                DataInputStream dataInputStream = new DataInputStream(new BufferedInputStream(socket.getInputStream()));

                //Method untuk meyimoan ke folder mana
                String methodGudang = dataInputStream.readUTF();
                textAreaLog.append("Action: " + methodGudang + "\n");

                // read parent file
                String parent = dataInputStream.readUTF();
                textAreaLog.append("Parent Folder: " + parent + "\n");

                //read the number of files from the client
                int number = dataInputStream.readInt();
                textAreaLog.append("File yang akan diterima berjumlah: " + number + "\n");

                ArrayList<File> files = new ArrayList<File>(number);

                //read file names, add files to arraylist
                for (int i = 0; i < number; i++) {
                    File file = new File(dataInputStream.readUTF());
                    files.add(file);
                }

                ArrayList<Long> size = new ArrayList<Long>(number);
                long longSize;
                for (int i = 0; i < number; i++) {
                    longSize = dataInputStream.readLong();
                    size.add(longSize);
                }

                int n = 0;
                byte[] buf = new byte[4092];

                path = Paths.get(
                        textFieldDirectory.getText()
                        + File.separator
                        + methodGudang + File.separator
                        + getDate() + " - " + parent);

                Files.createDirectories(path);

                textAreaLog.append("Direktori: " + path + " sudah dibuat" + "\n");
                textAreaLog.append("Memulai proses upload: " + "\n");

                String start = getDateTime();

                for (int i = 0; i < files.size(); i++) {

                    long fileSize = size.get(i);
                    textAreaLog.append("File Diterima: " + files.get(i).getPath() + " size: " + fileSize + "\n");

                    //create a new fileoutputstream for each new file with fileParent
                    FileOutputStream fileOutputStream
                            = new FileOutputStream(
                                    path + File.separator
                                    + files.get(i).getName());

                    //read file
                    while (fileSize > 0 && (n = dataInputStream.read(buf, 0, (int) Math.min(buf.length, fileSize))) != -1) {
                        fileOutputStream.write(buf, 0, n);
                        fileSize -= n;
                    }

                    fileOutputStream.close();
                }

                try {
                    MyTelegram.sendMesssage(
                            "Pengambilan Foto " + methodGudang + "\n"
                            + "Data: " + parent + "\n"
                            + "Jumlah File: " + number + "\n"
                            + "Start: " + start + "\n"
                            + "Finish: " + getDateTime() + "\n"
                            + "Silahkan lihat di server direktori " + path
                    );
                    textAreaLog.append("Notifikasi telegram terkirim \n");
                } catch (Exception e) {
                    textAreaLog.append("Notifikasi telegram tidak terkirim " + e.getMessage() + "\n");
                }

                dataInputStream.close();
            } catch (IOException ex) {
                textAreaLog.append(ex.getMessage());
            } finally {
                textAreaLog.append("Socket Thread " + socket.getPort() + " is Done " + "\n");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAboutMe;
    private javax.swing.JPanel jPanelServerLokal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCopyRight;
    private javax.swing.JLabel labelDirectory;
    private javax.swing.JLabel labelIpServer;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelPort;
    private javax.swing.JTextArea textAreaLog;
    private javax.swing.JTextField textFieldDirectory;
    private javax.swing.JTextField textFieldPort;
    // End of variables declaration//GEN-END:variables
}
